import { promises as fs } from 'fs';
import {Inter} from 'next/font/google'
import {Header} from "@/components/Header";
import {Footer} from "@/components/Footer";

const inter = Inter({subsets: ['latin']})
import './globals.css'

export const metadata = {
    title: 'Next JS Movies',
    description: 'Generated by create next app',
}

export default async function RootLayout({children}) {
    const file = await fs.readFile(process.cwd() + '/public/config.json', 'utf8');
    const configData = JSON.parse(file);
    const mainGenres = configData['mainGenres'];

    return (
        <html lang="en">
          <head/>
          <body className={inter.className}>
            <Header data={mainGenres} />
            <main>
              {children}
            </main>
            <Footer data={mainGenres}/>
          </body>
        </html>
    )
}
